name: Daily Value Bet Tennis

on:
  schedule:
    - cron: "30 7 * * *"
  workflow_dispatch:

jobs:
  daily-bet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Copy .env from secrets
        run: |
          echo "${{ secrets.ENVFILE }}" > .env
      - name: Run daily_run.py
        run: python src/daily_run.py
