name: Normalize CSV

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/normalize_csv.py'
      - 'data/*.csv'
      - '.github/workflows/normalize-csv.yml'
  pull_request:
    paths:
      - 'src/normalize_csv.py'
      - 'data/*.csv'
      - '.github/workflows/normalize-csv.yml'

jobs:
  normalize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run normalization script
        run: python src/normalize_csv.py

      - name: Upload normalized CSVs
        uses: actions/upload-artifact@v4
        with:
          name: normalized-csv
          path: data/*.norm.csv
